# Generated by Django 3.2 on 2021-04-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210428_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('대기중', '대기중'), ('결제대기', '결제대기'), ('환불', '환불'), ('결제완료', '결제완료')], default='대기중', max_length=32, verbose_name='상태'),
        ),
    ]
